name: Build documentation

on:
  push:
    tags:
      - "*"

jobs:
  test:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install cmake pybind11 numpy tox

      - name: Build docs
        run: |
          python setup.py build_ext --inplace
          cp build/lib*/rds2py/lib_rds_parser* src/rds2py/
          tox -e docs
          touch ./docs/_build/html/.nojekyll

      - name: GH Pages Deployment
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./docs/_build/html
          clean: true # Automatically remove deleted files from the deploy branch
